services:
  - type: web
    name: pick-ai-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PICK_SECRET_KEY
        generateValue: true
      - key: PICK_LLM_MODE
        value: local
