services:
  - type: web
    name: pick-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PICK_SECRET_KEY
        generateValue: true
